[package]
name = "image-cropper"
version = "0.1.0"
edition = "2022"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
image = "0.24.3"
js-sys = "0.3.60"
console_error_panic_hook = "0.1.7"
